 USGS/SLU Moment Tensor Solution
 ENS  2020/11/08 14:10:07:0  41.53  -70.97  15.1 4.0 Massachusetts
 
 Stations used:
   IU.HRV LD.BRNJ LD.FLET LD.KSCT LD.MCVT LD.NCB LD.ODNJ 
   LD.PAL LD.UNH N4.H62A N4.J59A N4.J61A N4.K62A N4.L61B 
   N4.L64A N4.M63A N4.N62A NE.BCX NE.TRY NE.WES NE.WSPT 
   US.LBNH 
 
 Filtering commands used:
   cut o DIST/3.3 -40 o DIST/3.3 +50
   rtr
   taper w 0.1
   hp c 0.03 n 3 
   lp c 0.10 n 3 
   br c 0.12 0.25 n 4 p 2
 
 Best Fitting Double Couple
  Mo = 3.39e+21 dyne-cm
  Mw = 3.62 
  Z  = 7 km
  Plane   Strike  Dip  Rake
   NP1      214    52   102
   NP2       15    40    75
  Principal Axes:
   Axis    Value   Plunge  Azimuth
    T   3.39e+21     79     174
    N   0.00e+00     10      27
    P  -3.39e+21      6     296

 Moment Tensor: (dyne-cm)
    Component   Value
       Mxx    -4.98e+20
       Mxy     1.29e+21
       Mxz    -7.96e+20
       Myy    -2.73e+21
       Myz     3.75e+20
       Mzz     3.22e+21
                                                     
                                                     
                                                     
                                                     
                     -------------#                  
                 -------------------###              
              ------------------#####-----           
             ----------------#########-----          
           ---------------#############------        
            ------------################------       
          P ----------##################-------      
        -   ---------####################-------     
        -----------######################-------     
       -----------#######################--------    
       ----------########################--------    
       ----------##########   ##########---------    
       ---------########### T ##########---------    
        --------###########   ##########--------     
        -------########################---------     
         ------#######################---------      
          -----######################---------       
           ----#####################---------        
             --###################---------          
              --################----------           
                 #############---------              
                     ####----------                  
                                                     
                                                     
                                                     
 Global CMT Convention Moment Tensor:
      R          T          P
  3.22e+21  -7.96e+20  -3.75e+20 
 -7.96e+20  -4.98e+20  -1.29e+21 
 -3.75e+20  -1.29e+21  -2.73e+21 


Details of the solution is found at

http://www.eas.slu.edu/eqc/eqc_mt/MECH.NA/20201108141007/index.html
