 USGS/SLU Moment Tensor Solution
 ENS  2021/08/13 11:57:35:0  35.88  -84.90   1.0 3.5 Tennessee
 
 Stations used:
   CO.CASEE CO.HODGE CO.PAULI ET.CPCT IM.TKL IU.WCI IU.WVT 
   N4.R49A N4.R50A N4.S51A N4.T47A N4.T50A N4.U49A N4.V48A 
   N4.V53A N4.V55A N4.W50A N4.W52A N4.X48A N4.X51A N4.Y52A 
   NM.BLO NM.USIN US.GOGA US.LRAL US.TZTN 
 
 Filtering commands used:
   cut o DIST/3.3 -40 o DIST/3.3 +50
   rtr
   taper w 0.1
   hp c 0.03 n 3 
   lp c 0.10 n 3 
 
 Best Fitting Double Couple
  Mo = 8.32e+21 dyne-cm
  Mw = 3.88 
  Z  = 8 km
  Plane   Strike  Dip  Rake
   NP1       41    60   -87
   NP2      215    30   -95
  Principal Axes:
   Axis    Value   Plunge  Azimuth
    T   8.32e+21     15     129
    N   0.00e+00      2     219
    P  -8.32e+21     75     318

 Moment Tensor: (dyne-cm)
    Component   Value
       Mxx     2.70e+21
       Mxy    -3.50e+21
       Mxz    -2.89e+21
       Myy     4.47e+21
       Myz     3.03e+21
       Mzz    -7.18e+21
                                                     
                                                     
                                                     
                                                     
                     ##############                  
                 ############---------#              
              ##########------------------           
             ########---------------------#          
           ########-----------------------###        
          #######------------------------#####       
         #######-------------------------######      
        #######-------------------------########     
        ######----------   -------------########     
       ######----------- P ------------##########    
       ######-----------   -----------###########    
       #####-------------------------############    
       #####-----------------------##############    
        ####----------------------##############     
        ####--------------------################     
         ###------------------#################      
          ###---------------############   ###       
           ##-------------############## T ##        
             #--------##################             
              ############################           
                 ######################              
                     ##############                  
                                                     
                                                     
                                                     
 Global CMT Convention Moment Tensor:
      R          T          P
 -7.18e+21  -2.89e+21  -3.03e+21 
 -2.89e+21   2.70e+21   3.50e+21 
 -3.03e+21   3.50e+21   4.47e+21 


Details of the solution is found at

http://www.eas.slu.edu/eqc/eqc_mt/MECH.NA/20210813115735/index.html
