#!/bin/sh

#####
#	clean up after a run or reset for a re-run
#	Reason:  if the data files in DAT.REG are changed, we must
#	reset to that the plots are correct
#####

rm -fr *[ZRT] *obs *pre
rm -fr Oout*
