#!/bin/sh

#####
#	cleanup
#####

for DIR in 0000 0001 0002 0003 0004 0005 0006 0007 0008 0009 0010 0011 0012 0013 0014 0015 0016 0017 0018 0019 0020
do
rm -f file96

HS=`echo $DIR | awk '{print $1/10.0}' `


if [ ! -d ${DIR} ]
then
	mkdir ${DIR}
fi

for GCARC in  50 
do
hudson96 -HS ${HS}  -TEL ../MODELS/tak135sph.mod -GCARC ${GCARC} -NPTS 4096 -DT 0.025   -SRC ../MODELS/korea.mod

hpulse96 -V -p -l 1 >> file96
done

cd ${DIR}
f96tosac -T < ../file96

cd ..

done

#####
#   make a depth record section
#####

gsac << EOF
cut b b 50
r */*.ZEX
bg plt
prs evdp reverse sa 0.0 amp 0.2 color 4 shd pos
quit
EOF

plotnps -F7 -W10 -EPS -K < PRS001.PLT > prs001.eps
convert -trim prs001.eps prs001.png
