 USGS/SLU Moment Tensor Solution
 ENS  2021/08/13 11:57:35:0  35.88  -84.90   1.0 3.5 Tennessee
 
 Stations used:
   CO.CASEE CO.HODGE CO.PAULI ET.CPCT IM.TKL IU.WCI IU.WVT 
   N4.R49A N4.R50A N4.S51A N4.T47A N4.T50A N4.U49A N4.V48A 
   N4.V53A N4.V55A N4.W50A N4.W52A N4.X48A N4.X51A N4.Y52A 
   NM.BLO NM.USIN US.GOGA US.LRAL US.TZTN 
 
 Filtering commands used:
   cut o DIST/3.3 -40 o DIST/3.3 +50
   rtr
   taper w 0.1
   hp c 0.03 n 3 
   lp c 0.10 n 3 
 
 Best Fitting Double Couple
  Mo = 1.26e+22 dyne-cm
  Mw = 4.00 
  Z  = 1 km
  Plane   Strike  Dip  Rake
   NP1       65    80    93
   NP2      230    10    75
  Principal Axes:
   Axis    Value   Plunge  Azimuth
    T   1.26e+22     55     338
    N   0.00e+00      3     245
    P  -1.26e+22     35     153

 Moment Tensor: (dyne-cm)
    Component   Value
       Mxx    -3.00e+21
       Mxy     1.95e+21
       Mxz     1.08e+22
       Myy    -1.16e+21
       Myz    -4.89e+21
       Mzz     4.16e+21
                                                     
                                                     
                                                     
                                                     
                     --------------                  
                 ----#################-              
              ----#######################-           
             --############################          
           --################################        
          --###########   ####################       
         --############ T ####################-      
        --#############   ##################----     
        -#################################------     
       --##############################----------    
       --##########################--------------    
       -########################-----------------    
       -####################---------------------    
        -###############------------------------     
        -#########------------------------------     
         -##-----------------------------------      
          -----------------------   ----------       
           ---------------------- P ---------        
             --------------------   -------          
              ----------------------------           
                 ----------------------              
                     --------------                  
                                                     
                                                     
                                                     
 Global CMT Convention Moment Tensor:
      R          T          P
  4.16e+21   1.08e+22   4.89e+21 
  1.08e+22  -3.00e+21  -1.95e+21 
  4.89e+21  -1.95e+21  -1.16e+21 


Details of the solution is found at

http://www.eas.slu.edu/eqc/eqc_mt/MECH.NA/20210813115735/index.html
