#!/bin/sh

#####
#	cleanup
#####

#for HS in 010 040 100 600
for HS in 010 100 600
do
rm -f file96

DIR=${HS}0
if [ ! -d w${DIR} ]
then
	mkdir w${DIR}
else
        rm -fr w${DIR}
	mkdir w${DIR}
fi

for GCARC in 50
do

#####
# do the water model
#####
hudson96 -HS ${HS}  -TEL ../MODELS/tak135sph.mod -SRC ../MODELS/sphavg.mod -GCARC ${GCARC} -NPTS 4096 -DT 0.1   

hpulse96 -V -p -l 1 >> file96
done

cd w${DIR}
f96tosac -T < ../file96

cd ..

#####
#	do the reference model
#####

if [ ! -d ${DIR} ]
then
	mkdir ${DIR}
else
        rm -fr ${DIR}
	mkdir ${DIR}
fi

for GCARC in 50
do
hudson96 -HS ${HS}  -TEL ../MODELS/tak135sph.mod  -GCARC ${GCARC} -NPTS 4096 -DT 0.1   

hpulse96 -V -p -l 1 >> file96
done

cd ${DIR}
f96tosac -T < ../file96
../DOANNOTATE

cd ..

done
