#!/bin/sh

rm -f */*
rm -f hspec*

# define P velocity of surface km/s
VP="5.0"
VS="2.89"
RHO="2.50"
# define the force in dynes
# define mg in uits of dyne - this is the spall mass * g
# 1000 metric tone and g = 9..8 m/s/s
# = 9.8* 10^6  kg m/s^2 = 9.8*10^11 dynes
MG="9.80E+11"

rm -f Source.txt
echo MG = ${MG} dyne >> source.txt


#####
#    create a simple velocity model
#    note that the proposed depths at in the same layer as the surface
#####
cat > CUS.mod << EOF
MODEL.01
CUS Model with Q from simple gamma values
ISOTROPIC
KGS
FLAT EARTH
1-D
CONSTANT VELOCITY
LINE08
LINE09
LINE10
LINE11
  H(KM) VP(KM/S) VS(KM/S) RHO(GM/CC)   QP   QS  ETAP  ETAS  FREFP  FREFS
  1.0000  5.0000  2.8900  2.5000 0.172E-02 0.387E-02 0.00  0.00  1.00  1.00 
  9.0000  6.1000  3.5200  2.7300 0.160E-02 0.363E-02 0.00  0.00  1.00  1.00 
 10.0000  6.4000  3.7000  2.8200 0.149E-02 0.336E-02 0.00  0.00  1.00  1.00 
 20.0000  6.7000  3.8700  2.9020 0.000E-04 0.000E-04 0.00  0.00  1.00  1.00 
  0.0000  8.1500  4.7000  3.3640 0.194E-02 0.431E-02 0.00  0.00  1.00  1.00 
EOF

#####
#    crate a file for distances
#####
cat > dfile << EOF
010.00 0.05 2048 -10 6
200.00 0.05 2048 -10 6
EOF
#####
#    create synthetics for a source at the surface
#    To avoid some numerical problems, the source is placed
#    at a depth of 1 meter = 0.001 km
#    The Green's functions are saved in the directory FORCE.
#    Since the Green's functions here implicitly for a step source
#    time function, we must take a derivative to get the
#    real Green's function for an impulsive source time function.
#    which are obtained using the hpulse -V command since
#    velocity due to a step is the displacmment due to an impulse, e.g.,
#    Green;s function.  The -p -l 1 tapers the spectrum to make a nice
#    synthetic
#####
hprep96 -M CUS.mod -HS 0.001 -HR 0.0 -EXF -d dfile
hspec96
mkdir FORCE
hpulse96 -V -p -l 1 | ( cd FORCE; f96tosac -G )
#####
#    go the the FORCE directory and apply the
#    force using hte gsac MT command
#    In addition convolve the Green function with the 
#    Day, Rimer, Cherry (1983) source time function, which is implemented 
#    in gsac as the double integral  so we take the second derivaive.
#####
(cd FORCE
for T in *ZEX
do
B=`basename $T .ZEX`
gsac << EOF
#  apply the mechanism
mt to zrt FD ${MG} AZ 0.0 FILE ${B}
w
mv T.Z $B.Z
mv T.R $B.R
mv T.T $B.T
#  create the source function
#  by using the par2 pulse with duration of 1.0 sec and then
#  taking the second derivative
fg par2 1.0  delta 0.05 npts 512 
w imp.sac
r imp.sac
dif
dif
ch o 0.0
w
#    convolve the source time function with the Day, Rimer, Cherry force
#    function. Use the beginning of the theoretical pulse as a reference
#    to preserve travel times
r ${B}.Z ${B}.R
convolve zero a file imp.sac
w prepend force.
q
EOF
done
)

#####
#    now to test the Day McLaughlin (1991) representation
#    of the spall as an opening horotontal crack
#    we use the same par2 source pusle that then multiply the
#    force by VP^2/source_depth


for EVDP in 0.1 0.2 0.3 0.4
do
hprep96 -M CUS.mod -HS ${EVDP}  -HR 0.0 -EQEX -d dfile
hspec96
mkdir CRACK.${EVDP}
hpulse96 -V -p -l 1 | ( cd CRACK.${EVDP}; f96tosac -G )
(cd CRACK.${EVDP}
for T in *ZEX
do
B=`basename $T .ZEX`
EVDP=`saclhdr -EVDP $T`
######
#  the equivalent moment is MG VP^2 / H 
#  here we have H in km and VP in km/s
#  thus the moment is MG (dynes from above) * (BP^2 / H) * 1.0e+06
# We assume lambda = mu
# To get the units correct, e.g., the moment must be given in terms of
# dyne - cm
# MG = force in dynes
# HS = EVDP  = km = 10^5 cm
# VP   = km/s = 10^5 cm/s
# We must input m g VP^2/depth
# 
# Equation (16) of Day and McLaughlin(1991) has
# 
#                             |  A   0   0  |
#             Mg   VP^2       |             |
# M(omega) = ---------------- |  0   A   0  |
#             HS (i omega)^2  |             |
#                             |  0   0   B  |
#                             
#
# where A = lambda/(lambda + 2 mu ) = ( Vp^2 - 2 Vs^2 )/ Vp^2
#####
MZZ=`echo ${MG} ${VP} ${VS} ${EVDP} | awk '{printf "%10.3e", $1*$2*$2*1.0E+05/($4)    }' `
MXX=`echo ${MG} ${VP} ${VS} ${EVDP} | awk '{printf "%10.3e", $1*$2*$2*1.0E+05/($4)* ($2*$2 - 2*$3*$3)/($2*$2)}' `
MYY=`echo ${MG} ${VP} ${VS} ${EVDP} | awk '{printf "%10.3e", $1*$2*$2*1.0E+05/($4)* ($2*$2 - 2*$3*$3)/($2*$2)}' `
echo EVDP = ${EVDP} MXX = ${MXX} dyne-cm >> ../source.txt
echo EVDP = ${EVDP} MYY = ${MYY} dyne-cm >> ../source.txt
echo EVDP = ${EVDP} MZZ = ${MZZ} dyne-cm >> ../source.txt
gsac << EOF
mt to zrt MZZ ${MZZ} MXX ${MXX} MYY ${MYY} AZ 0.0 FILE $B
w
mv T.Z $B.Z
mv T.R $B.R
mv T.T $B.T
fg par2 1.0  delta 0.05 npts 512 
w imp.sac
rh imp.sac
ch o 0.0
wh
r ${B}.Z ${B}.R
convolve zero a file imp.sac
w prepend crack.
q
EOF
done
)

done



