#!/bin/sh

PROTO=FIG1

#####
#    define colors for calplt
#####
cat > red << EOF
NEWPEN
2
EOF
cat > blue << EOF
NEWPEN
4
EOF
cat > black << EOF
NEWPEN
1
EOF
cat > green << EOF
NEWPEN
3
EOF

#####
#    initialize
#####
rm -f grid.d
for X in 0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0 8.0  9.0  
do
	cat red >> grid.d
	echo LINE >> grid.d
	echo $X 0.0 $X 8.0 >> grid.d
	cat green >> grid.d
	for inc in 1 2 3
	do
		X=`echo $X | awk '{print $1 + 0.25}'`
		echo LINE >> grid.d
		echo $X 0.0 $X 8.0 >> grid.d
	done
done
for Y in 0 1 2 3 4 5 6 7 
do
	cat red >> grid.d
	echo LINE >> grid.d
	echo 0.0 $Y  10.0 $Y >> grid.d
	cat green >> grid.d
	for inc in 1 2 3
	do
		Y=`echo $Y | awk '{print $1 + 0.25}'`
		echo LINE >> grid.d
		echo 0.0 $Y 10.0 $Y  >> grid.d
	done
done
echo PEND >> grid.d
calplt < grid.d 
mv CALPLT.PLT GRID.PLT


calplt << EOF
PLOT
3 3 -3
NEWPEN
1
SFILL
'CI' 0.15 0.0 0.0 
ARROW
0.0 0.0 0.0 2.0 .false.
CENTER
0.0 2.2 0.15 'N' 0.0
NEWPEN
1
ARROW
0.0 0.0 -1.4 1.4 .false.
SUBSC
-1.6 1.6 0.20 'x' 1 'r ' 1
ARC
0.0 0.0 1.0 90. -225 .true.
GFONT
4
CENTER
0.2 -0.4 0.20 'f' 0.0
GFONT
0
NEWPEN
1
PLOT
-3 -3 -3
PEND
EOF

cat GRID.PLT CALPLT.PLT > ${PROTO}.PLT
plotnps -F7 -W10 -EPS -K < ${PROTO}.PLT > ${PROTO}.eps
mv CALPLT.PLT ${PROTO}.PLT
DOPLTPNG ${PROTO}.PLT

rm -f red green black blue
rm -f grid.d
