#!/bin/sh
set -x
#####
#    cleanup
#####
rm -f *.PLT *.png

mod="mod00"
ZMAX=35
WIDTH=35
#WIDTH=15
#define contour values
cat >kv_file<<EOF
2.0
2.5
3.0
3.25
3.5
3.75
4.0
4.25
4.5
4.7
5.0
EOF
#define contour values to be annotated
cat > ka_file <<EOF
2.0
2.5
3.0
3.5
4.0
4.25
4.5
5.0
EOF
cat > mad1 <<EOF
-23.612 43.59 'ORIGIN' '$mod.000.000'
-23.2382 44.024 'MS03' '$mod.000.000'
-23.1050 44.2198 'MS04' '$mod.000.001'
-22.9060 44.4638 'MS05' '$mod.000.002'
-22.8124 44.8289 'MS07' '$mod.000.003'
-22.7548 45.1131 'MS08' '$mod.000.004'
-22.4826 45.3982 'MS09' '$mod.000.005'
-22.4736 45.5668 'MS10' '$mod.000.006'
-22.4374 45.915 'MS12' '$mod.000.007'
-22.3575 46.0879 'MS13' '$mod.000.008'
-22.0855 46.4091 'MS15' '$mod.000.009'
-21.9357 46.543 'MS16' '$mod.000.010'
-21.4093 47.1029 'MS19' '$mod.000.011'
-21.3316 47.2715 'MS20' '$mod.000.012'
-21.2389 47.3825 'MS21' '$mod.000.013'
EOF
LL='-LAT1 -23.712 -LON1 43.59 -LAT2 -21.1389 -LON2 47.3825'
prfmod96 -X0 1.75 -XLEN 5.7 -YLEN 3 -ZMAX ${ZMAX} -C mad1  ${LL} \
 -W ${WIDTH} -KA ka_file -KV kv_file
mv PRFMOD96.PLT NONE.PLT

prfmod96 -X0 1.75 -XLEN 5.7 -YLEN 3 -ZMAX ${ZMAX} -C mad1  ${LL} \
 -W ${WIDTH} -KA ka_file -KV kv_file -BL -BO 1.5
mv PRFMOD96.PLT LEFT.PLT

prfmod96 -X0 1.75 -XLEN 5.7 -YLEN 3 -ZMAX ${ZMAX} -C mad1  ${LL} \
 -W ${WIDTH} -KA ka_file -KV kv_file -BR 
mv PRFMOD96.PLT RIGHT.PLT

prfmod96 -X0 1.75 -XLEN 5.7 -YLEN 3 -ZMAX ${ZMAX} -C mad1  ${LL} \
 -W ${WIDTH} -KA ka_file -KV kv_file -BT  -BO 1.0
mv PRFMOD96.PLT TOP.PLT

prfmod96 -X0 1.75 -XLEN 5.7 -YLEN 3 -ZMAX ${ZMAX} -C mad1  ${LL} \
 -W ${WIDTH} -KA ka_file -KV kv_file -BB  
mv PRFMOD96.PLT BOTTOM.PLT

#####
#    convert PLT to PNG
######

for i  in *.PLT
do
B=`basename $i .PLT`
plotnps -F7 -W10 -EPS -K < $i > t.eps
convert -trim t.eps -background white -alpha remove -alpha off ${B}.png
rm t.eps
done

