#!/bin/sh


rm -f SYM.PLT
fmplot -UP  -X0 2 -Y0 19 -RAD 1.25 -FMPLMN -XX -1 -YY -1 -ZZ 1 -P  -TT "P"
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 5 -Y0 19 -RAD 1.25 -FMPLMN -XX -1 -YY -1 -ZZ 1 -SV -TT "SV"
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 8 -Y0 19 -RAD 1.25 -TT "SH" 
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 11 -Y0 19 -RAD 1.25 -XX -1 -YY -1 -ZZ 1 -pol -TT "POL" -TP -NOFMTP -NONODAL
cat FMPLOT.PLT >> SYM.PLT
calplt << EOF
NEWPEN
1
PLOT
12.8 18.8 -3
LEFT
 0.0  0.0 0.4 'DD' 0.0
LEFT 
1.1 0.1 0.2 "M=" 0.0
LEFT 
1.5  0.6 0.2 " -1  0  0" 0.0
LEFT 
1.5  0.1 0.2 "  0 -1  0" 0.0
LEFT 
1.5 -0.4 0.2 "  0  0  2" 0.0
LINE
1.6 -0.5 1.6 0.9
LINE
3.5 -0.5 3.5 0.9
3.4 -0.5 3.4 0.9
PLOT
-12.8 -18.8 -3
PEND
EOF
cat CALPLT.PLT >> SYM.PLT

fmplot -UP  -X0 2 -Y0 16 -RAD 1.25 -FMPLMN -XZ 1 -P  
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 5 -Y0 16 -RAD 1.25 -FMPLMN -XZ 1 -SV 
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 8 -Y0 16 -RAD 1.25 -FMPLMN -XZ 1 -SH -NONODAL
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 11 -Y0 16 -RAD 1.25 -XZ 1 -pol -NOFMTP -NONODAL
cat FMPLOT.PLT >> SYM.PLT
calplt << EOF
NEWPEN
1
PLOT
12.8 15.8 -3
LEFT
 0.0  0.0 0.4 'DS' 0.0
LEFT 
1.1 0.1 0.2 "M=" 0.0
LEFT 
1.5  0.6 0.2 "  0  0  1" 0.0
LEFT 
1.5  0.1 0.2 "  0  0  0" 0.0
LEFT 
1.5 -0.4 0.2 "  1  0  0" 0.0
LINE
1.6 -0.5 1.6 0.9
LINE
3.5 -0.5 3.5 0.9
PLOT
-12.8 -15.8 -3
PEND
EOF
cat CALPLT.PLT >> SYM.PLT

fmplot -UP  -X0 2 -Y0 13 -RAD 1.25 -FMPLMN -XX 1 -YY -1 -P  
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 5 -Y0 13 -RAD 1.25 -FMPLMN -XX 1 -YY -1 -SV  
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 8 -Y0 13 -RAD 1.25 -FMPLMN -XX 1 -YY -1 -SH  
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 11 -Y0 13 -RAD 1.25 -XX 1 -pol  -YY -1 -
cat FMPLOT.PLT >> SYM.PLT
calplt << EOF
NEWPEN
1
PLOT
12.8 12.8 -3
LEFT
 0.0  0.0 0.4 'SS' 0.0
LEFT 
1.1 0.1 0.2 "M=" 0.0
LEFT 
1.5  0.6 0.2 "  1  0  0" 0.0
LEFT 
1.5  0.1 0.2 "  0 -1  0" 0.0
LEFT 
1.5 -0.4 0.2 "  0  0  0" 0.0
LINE
1.6 -0.5 1.6 0.9
LINE
3.5 -0.5 3.5 0.9
PLOT
-12.8 -12.8 -3
PEND
EOF
cat CALPLT.PLT >> SYM.PLT

fmplot -UP  -X0 2 -Y0 10 -RAD 1.25 -FMPLMN -XX 1 -YY 1 -ZZ 1 -P  
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 5 -Y0 10 -RAD 1.25 
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 8 -Y0 10 -RAD 1.25 
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 11 -Y0 10 -RAD 1.25 
cat FMPLOT.PLT >> SYM.PLT
calplt << EOF
NEWPEN
1
PLOT
12.8 9.8 -3
LEFT
 0.0  0.0 0.4 'EX' 0.0
LEFT
1.1 0.1 0.2 "M=" 0.0
LEFT 
1.5  0.6 0.2  "  1  0  0" 0.0
LEFT 
1.5  0.1 0.2  "  0  1  0" 0.0
LEFT 
1.5 -0.4 0.2 "  0  0  1" 0.0
LINE
1.6 -0.5 1.6 0.9
LINE
3.5 -0.5 3.5 0.9
PLOT
-12.8 -9.8 -3
PEND
EOF
cat CALPLT.PLT >> SYM.PLT

fmplot -UP  -X0 2 -Y0 7 -RAD 1.25 -FMPLMN  -P   -F3 1
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 5 -Y0 7 -RAD 1.25 -FMPLMN  -SV  -F3 1
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 8 -Y0 7 -RAD 1.25 
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 11 -Y0 7 -RAD 1.25 -pol   -F3 1
cat FMPLOT.PLT >> SYM.PLT
calplt << EOF
NEWPEN
1
LEFT
12.8 6.8 0.4 'VF' 0.0
LEFT
13.9 6.9 0.2 'F=[ 0, 0, 1 ]' 0.0
PEND
EOF
cat CALPLT.PLT >> SYM.PLT

fmplot -UP  -X0 2 -Y0 4 -RAD 1.25 -FMPLMN  -P   -F1 1
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 5 -Y0 4 -RAD 1.25 -FMPLMN  -SV  -F1 1
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 8 -Y0 4 -RAD 1.25 -FMPLMN  -SH  -F1 1
cat FMPLOT.PLT >> SYM.PLT
fmplot -UP  -X0 11 -Y0 4 -RAD 1.25 -pol   -F1 1
cat FMPLOT.PLT >> SYM.PLT
calplt << EOF
NEWPEN
1
LEFT
12.8 3.8 0.4 'HF' 0.0
LEFT
13.9 3.9 0.2 'F=[ 1, 0, 0 ]' 0.0
PEND
EOF
cat CALPLT.PLT >> SYM.PLT


plotnps -F7 -W10 -EPS -K < SYM.PLT > sym.eps
#ed sym.eps << EOF
#g/8.640000 1 (P) ShowEqui/s/P/ /
#g/8.640000 1 (T) ShowEqui/s/T/ /
#w
#q
#EOF

#rm -f FMPLOT.PLT CALPLT.PLT CALPLT.cmd
