#!/bin/sh


#####
#    annotate the Sac file with sP pP PP and PcP picks
#####

for i in *.[ZRT]??
do

GCARC=`saclhdr -GCARC $i`
EVDP=`saclhdr -EVDP $i`

taup_time -H ${EVDP} -deg ${GCARC} -ph "pP,sP,PP,PcP" -mod ak135 > j 2>&1

echo DOANNOTATE $GCARC $EVDP
#####
#    now get the phase times
#####
pP=`grep " pP " j | awk '{print $4}' | head -1 | tail -1 `
sP=`grep " sP " j | awk '{print $4}' | head -1 | tail -1`
PP=`grep " PP " j | awk '{print $4}' | head -1 | tail -1 `
PcP=`grep " PcP " j | awk '{print $4}' | head -1 | tail -1`
gsac << EOF
rh $i
ch KT3 pP T3 ${pP}
ch KT4 sP T4 ${sP}
ch KT5 PP T5 ${PP}
ch KT6 PcP T6 ${PcP}
wh
quit
EOF
done

rm -f j
