#!/bin/sh
rm -f *.gif

for HS in 0100 6000
do
for SRC in DS SS DD EX
do
for CMP in Z 
do
for GCARC in 30 50 70 90
do
case $GCARC in
	30) DIST=033 ;;
	40) DIST=044 ;;
	50) DIST=055 ;;
	60) DIST=066 ;;
	70) DIST=077 ;;
	80) DIST=088 ;;
	90) DIST=100 ;;
esac

gsac << EOF
cut a -10 a 200
fileid name
r  ${HS}/${DIST}*.${CMP}${SRC} ${GREENDIR}/AK135.TEL/${HS}/${DIST}*.${CMP}${SRC}
subf master 1
w  diff zero
r  ${GREENDIR}/AK135.TEL/${HS}/${DIST}*.${CMP}${SRC} ${HS}/${DIST}*.${CMP}${SRC} diff
color list black blue red
bg plt
ylim all
p 
plotgif -K -C16 < P001.PLT > ${GCARC}.${HS}.${CMP}${SRC}.gif
quit
EOF
done
done
done
done

rm -f diff zero
