#!/bin/sh



for MOD in tak135sph.mod Ttak135sph.mod Ftak135sph.mod FTtak135sph.mod
do
echo Model: $MOD

#for DEPTH in 10 40 100 200 300 400 500  600 700
for DEPTH in  700 

do
echo \
"GCARC  EVDP   TpP(sec) p(pP)(s/km)    T*(pP)   TsP(sec) p(sP)(s/km)    T*(sP)"
#DDDDD DDDDD FFFFFFF.ff FFFFFFF.ff FFFFFFF.ff FFFFFFF.ff FFFFFFF.ff FFFFFFF.ff
echo "---------------------------------------------------------------------------------"
#for GCARC in 0.01 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 30 40 50 60 70 80 90 100 110 120 130 140
#for GCARC in 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 
for GCARC in 30 40 60 90
do


export pP=`time96 -GCARC $GCARC -EVDP $DEPTH -pP -M $MOD`
export sP=`time96 -GCARC $GCARC -EVDP $DEPTH -sP -M $MOD`
export RAYpP=`time96 -GCARC $GCARC -EVDP $DEPTH -pP -RAYP -M $MOD`
export RAYsP=`time96 -GCARC $GCARC -EVDP $DEPTH -sP -RAYP -M $MOD`
export TSpP=`time96 -GCARC $GCARC -EVDP $DEPTH -pP -TS -M $MOD`
export TSsP=`time96 -GCARC $GCARC -EVDP $DEPTH -sP -TS -M $MOD`

echo ${GCARC} ${DEPTH}  ${pP} ${RAYpP} ${TSpP} ${sP} ${RAYsP} ${TSsP}  | awk '{printf "%5d %5d %10.2f %10.2f %10.2f %10.2f %10.2f %10.2f\n", $1, $2, $3, $4 , $5 , $6, $7 ,$8}' 

done
echo "---------------------------------------------------------------------------------"
done

done
