 USGS/SLU Moment Tensor Solution
 ENS  2021/08/13 11:57:35:0  35.88  -84.90   1.0 3.5 Tennessee
 
 Stations used:
   CO.CASEE CO.HODGE CO.PAULI ET.CPCT IM.TKL IU.WCI IU.WVT 
   N4.R49A N4.R50A N4.S51A N4.T47A N4.T50A N4.U49A N4.V48A 
   N4.V53A N4.V55A N4.W50A N4.W52A N4.X48A N4.X51A N4.Y52A 
   NM.BLO NM.USIN US.GOGA US.LRAL US.TZTN 
 
 Filtering commands used:
   cut o DIST/3.3 -40 o DIST/3.3 +50
   rtr
   taper w 0.1
   hp c 0.03 n 3 
   lp c 0.10 n 3 
 
 Best Fitting Double Couple
  Mo = 1.02e+22 dyne-cm
  Mw = 3.94 
  Z  = 1 km
  Plane   Strike  Dip  Rake
   NP1      265    75   -90
   NP2       85    15   -90
  Principal Axes:
   Axis    Value   Plunge  Azimuth
    T   1.02e+22     30     355
    N   0.00e+00     -0     265
    P  -1.02e+22     60     175

 Moment Tensor: (dyne-cm)
    Component   Value
       Mxx     5.08e+21
       Mxy    -4.44e+20
       Mxz     8.83e+21
       Myy     3.89e+19
       Myz    -7.72e+20
       Mzz    -5.12e+21
                                                     
                                                     
                                                     
                                                     
                     ##############                  
                 ######################              
              ###########   ##############           
             ############ T ###############          
           ##############   #################        
          ####################################       
         ######################################      
        ########################################     
        ########################################     
       #############--------------------------###    
       ######------------------------------------    
       ##---------------------------------------#    
       #----------------------------------------#    
        ---------------------------------------#     
        #------------------   ----------------##     
         #----------------- P ---------------##      
          #----------------   --------------##       
           ##-----------------------------###        
             ##-------------------------###          
              ####-------------------#####           
                 #######-------########              
                     ##############                  
                                                     
                                                     
                                                     
 Global CMT Convention Moment Tensor:
      R          T          P
 -5.12e+21   8.83e+21   7.72e+20 
  8.83e+21   5.08e+21   4.44e+20 
  7.72e+20   4.44e+20   3.89e+19 


Details of the solution is found at

http://www.eas.slu.edu/eqc/eqc_mt/MECH.NA/20210813115735/index.html
