#!/bin/sh
 
# Data file = ../NOISE/ACLRBHZASCBBHZ.WSTK
# alpha =     12.500
 
sdpegn96 -X0  5.10 -Y0  1.50 -XLEN  4.00 -YLEN  4.00 -XMIN  0.200     -XMAX   20.0     -YMIN  1.00 -YMAX  5.00 -PER  -R -U -NOBOX -XLOG -YLIN 
 
sacspc96 -X0  1.30 -Y0  1.50 -XLEN  3.00 -YLEN  4.00 -XMIN  0.200     -XMAX   20.0     -YMIN  0.100     -YMAX   100. -PER   -NOBOX -XLOG -YLOG -f ../NOISE/ACLRBHZASCBBHZ.WSTK
