#!/bin/sh

#####
#	compute the free oscillation frequencies and the eigenfunctions
#####
DOEGN tak135-f
#####
#	now compute the synthetics for a specific moment tensor that represents
#	the following cases
#	
#	Source	STK	DIP	RAKE Mw [M0(dyne-cm)] Src-Rec Az
#       DS      45      90      90   2.6 [1.0E+20]       0
#       SS      22.5    90       0   2.6 [1.0E+20]       0
#       DD      45      45      90   2.6 [1.0E+20]       0
#       EX      Center of expansion  2.6 [1.0E+20]       0
#####
DOSYNSS
DOSYNDS
DOSYNDD
DOSYNEX
