 USGS/SLU Moment Tensor Solution
 ENS  2021/08/13 11:57:35:0  35.88  -84.90   1.0 3.5 Tennessee
 
 Stations used:
   CO.CASEE CO.HODGE CO.PAULI ET.CPCT IM.TKL IU.WCI IU.WVT 
   N4.R49A N4.R50A N4.S51A N4.T47A N4.T50A N4.U49A N4.V48A 
   N4.V53A N4.V55A N4.W50A N4.W52A N4.X48A N4.X51A N4.Y52A 
   NM.BLO NM.USIN US.GOGA US.LRAL US.TZTN 
 
 Filtering commands used:
   cut o DIST/3.3 -40 o DIST/3.3 +50
   rtr
   taper w 0.1
   hp c 0.03 n 3 
   lp c 0.10 n 3 
 
 Best Fitting Double Couple
  Mo = 1.35e+22 dyne-cm
  Mw = 4.02 
  Z  = 1 km
  Plane   Strike  Dip  Rake
   NP1      290    75   -90
   NP2      110    15   -90
  Principal Axes:
   Axis    Value   Plunge  Azimuth
    T   1.35e+22     30      20
    N   0.00e+00     -0     290
    P  -1.35e+22     60     200

 Moment Tensor: (dyne-cm)
    Component   Value
       Mxx     5.96e+21
       Mxy     2.17e+21
       Mxz     1.10e+22
       Myy     7.89e+20
       Myz     4.00e+21
       Mzz    -6.74e+21
                                                     
                                                     
                                                     
                                                     
                     ##############                  
                 ######################              
              #################   ########           
             ################## T #########          
           ####################   ###########        
          ####################################       
         ######################################      
        -----------#############################     
        ------------------######################     
       #-----------------------##################    
       #----------------------------#############    
       #-------------------------------##########    
       ##---------------------------------#######    
        #---------------   ------------------###     
        ##-------------- P --------------------#     
         ##-------------   --------------------      
          ###---------------------------------       
           ###------------------------------#        
             ###--------------------------#          
              #####--------------------###           
                 ########---------#####              
                     ##############                  
                                                     
                                                     
                                                     
 Global CMT Convention Moment Tensor:
      R          T          P
 -6.74e+21   1.10e+22  -4.00e+21 
  1.10e+22   5.96e+21  -2.17e+21 
 -4.00e+21  -2.17e+21   7.89e+20 


Details of the solution is found at

http://www.eas.slu.edu/eqc/eqc_mt/MECH.NA/20210813115735/index.html
