#!/bin/sh

#####
#    Note this assumes that gmt5 or gmt6 are installed
#####

#####
#    clean up
#####
rm -f  *.sac *.png

#####
#    Define the GREEN funciton directories
#    Here we use the AK135 teleseismic from 30 - 90 degrees
#####
GREEN=${GREENDIR}/AK135.TEL


#####
#    define epicenter location, depoth and origin time
#####
EVLA=0.0
EVLO=0.0
EVDP=10.0
HS=0100		# note this is the ID for a source depth of 10.0 km
STK=0
DIP=80
RAKE=0
MW=5.0
NZYEAR=2025
NZJDAY=025
NZHOUR=01
NZMIN=02
NZSEC=30
NZMSEC=456


#####
#    define stations
#    KSTNM KNETWK LATITUDE LONGITUDE 
#    this lisut of stations has 30 <= GCARC <=90 degrees
#    
#####
cat > sta.txt << EOF
LSZ IU -15.2779 28.1882
MACI IU 28.2502 -16.5082
RCBR IU -5.8274 -35.9014
KMBO IU -1.1271 37.2525
TRIS IU -37.0681 -12.3152
FURI IU 8.8952 38.6798
PAB IU 39.5446 -4.3499
ANTO IU 39.868 32.7934
GRFO IU 49.6909 11.2203
KIEV IU 50.7012 29.2242
GNI IU 40.148 44.741
KONO IU 59.6521 9.5946
SAML IU -8.9489 -63.1831
SJG IU 18.1091 -66.15
TRQA IU -38.0568 -61.9787
BBSR IU 32.3713 -64.6963
SDV IU 8.8839 -70.634
KEV IU 69.7565 27.0035
LCO IU -29.011 -70.7005
SFJD IU 66.9961 -50.6208
HRV IU 42.5064 -71.5583
OTAV IU 0.2376 -78.4508
KBS IU 78.9154 11.9385
PMSA IU -64.7744 -64.0489
SSPA IU 40.6358 -77.8876
DWPF IU 28.1103 -81.4327
MAKZ IU 46.808 81.977
CHTO IU -12345 -12345
HNR IU -12345 -12345
KMBO IU -12345 -12345
RAO IU -12345 -12345
WCI IU 38.2289 -86.2939
WVT IU 36.1297 -87.83
TEIG IU 20.2263 -88.2763
EOF

#####
#    for each station
#    find the appropriuate Green's function
#    and then make the synthetic.
#    Note for telesxeismic, the Green's functions are computed at 1.0 degree increments 
#    and this will affect any use of this data set
#
#    This relies on the structure of the Greeens functions and the W.CTL file
#    for the particular depth
#####
while read KSTNM KNETWK STLA STLO 
do
#####
#     compute distance ans aximuths
#####
        GCARC=`udelaz -EVLA $EVLA -EVLO $EVLO -STLA $STLA -STLO $STLO -GCARC`
        DIST=`udelaz -EVLA $EVLA -EVLO $EVLO -STLA $STLA -STLO $STLO -DIST`
        AZ=`udelaz -EVLA $EVLA -EVLO $EVLO -STLA $STLA -STLO $STLO -AZ`
        BAZ=`udelaz -EVLA $EVLA -EVLO $EVLO -STLA $STLA -STLO $STLO -BAZ`
#####
#       search over source depth These depths are the subdirectory
#       names in the Green's Function Directory
#####

cat > awkprog << FOE
# This works under gawk - on Solaris try nawk
BEGIN { MDIF = 10000.0 }
{DIF = $DIST - \$1 ;
if( DIF < 0 ) DIF = - DIF ;
if(DIF < MDIF) { MDIF = DIF ; Dfile = \$7 ; Rate = \$2 ; Dist = \$1 }
}
END { print Dfile , Rate, Dist }
FOE

        cat ${GREEN}/${HS}/W.CTL | \
                awk -f awkprog > j
        rm awkprog
	DFILE=`awk '{print $1}' < j | head -1`
	#####
	# now use gsac to make a synthetic
	#####
RAZ=`echo $BAZ | awk '{print $1 + 180}' `
TAZ=`echo $BAZ | awk '{print $1 + 180 + 90}' `
# cast station name into five characters for NNSSSSSCCCLL format
# implement a five character station name
SSSSS=`echo $KSTNM | awk '{
if(length($1) == 5)printf "%5s", $1
if(length($1)==4)printf "%4s_",$1 
if(length($1)==3)printf "%3s__",$1
if(length($1)==2)printf "%2s___",$1
if(length($1)==1)printf "%1s____",$1
}'`
gsac << EOF
#####
#    when reading the sytnhetics zero fill to make all synthetics
#    start to O and end at O +5000. Note because of the start time
#    of the Green's functions O will not exactly be 0.0 
#####
cut o 0 o 5000
#####
#    apply the source to make the time histories
#####
mt to ZRT MW $MW AZ $AZ STK $STK RAKE $RAKE DIP $DIP FILE ${GREEN}/${HS}/${DFILE}
w
cut off
rh T.Z T.R T.T
# the order is import here. The NZYEAR ... NZMSEC are just fields to define the
# timestamp of the first arrival. By synchronizing and setting these values
# everything is case in terms of human orogin time
#####
synchronize o
#
ch NZYEAR $NZYEAR NZJDAY $NZJDAY NZHOUR $NZHOUR NZMIN $NZMIN NZSEC $NZSEC NZMSEC $NZMSEC
ch EVLA $EVLA EVLO $EVLO EVDP $EVDP STLA $STLA STLO $STLO KNETWK $KNETWK
ch KSTNM $KSTNM
wh
#####
#    set header values for component orientation and azimuths
#####
rh T.Z
ch cmpinc 0 cmpaz 0
wh
rh T.R
ch cmpinc 90 cmpaz $RAZ
wh
rh T.T
ch cmpinc 90 cmpaz $TAZ
wh
q
EOF
mv T.Z ${KNETWK}${SSSSS}HHZ__.SAC
mv T.R ${KNETWK}${SSSSS}HHR__.SAC
mv T.T ${KNETWK}${SSSSS}HHT__.SAC
rm -f j

done < sta.txt

#####
#    make plots of record sections for ueach component
#####
gsac << EOF
bg plt
r *Z__.SAC
#title on l top size m text "Z component"
prs amp 0.1 gcarc ann name
mv PRS001.PLT Z.PLT
r *R__.SAC
#title on l top size m text "R component"
prs amp 0.1 gcarc
mv PRS002.PLT R.PLT
r *T__.SAC
#title on l top size m text "T component"
prs amp 0.1 gcarc
mv PRS003.PLT T.PLT
q
EOF

#####
#    make a map
#####
gsac << EOF
rh *HHZ*
map5 ep on st on kstnm on ray on
q
EOF
#####
#    use GMT 5+ to make the map
#####
sh map5.sh
EPSTOPNG map5.eps map5.png


#####
#   use ImageMagick to make PNG from the PLT files
#####

for i in [ZRT].PLT
do
B=`basename $i .PLT`
plotnps -F7 -W10 -EPS -K -S0.9 < $i > t.eps
convert -trim t.eps -background white -alpha remove -alpha off ${B}.png
rm t.eps
done

#####
#    rename the PNG files to indicate that they are from the Forward directory
#####
for i in *.png
do
	mv $i ../Figures/F_${i}
done


#####
#    clean up
#####
rm -fr PRS*.CTL
rm -f gmt* *.PLT

rm -f map5.eps map5.sh
