#!/bin/sh
 
# Data file = dvel.sac
# alpha =     50.000
 
sdpegn96 -X0  5.10 -Y0  1.50 -XLEN  4.00 -YLEN  4.00 -XMIN   4.00     -XMAX   100.     -YMIN  2.00 -YMAX  5.00 -PER  -R -U -NOBOX -XLOG -YLIN 
 
sacspc96 -X0  1.30 -Y0  1.50 -XLEN  3.00 -YLEN  4.00 -XMIN   2.00     -XMAX   200.     -YMIN  0.100E-03 -YMAX  0.100 -PER   -NOBOX -XLOG -YLOG -f dvel.sac
